name: ci

on:
  push:
  pull_request:

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          # Pas de dépendances runtime pour l'instant,
          # mais gardons la commande pour évoluer facilement
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: python -m unittest discover -s tests -p "test_*.py" -v