name: ci

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint (ruff + black)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.6.9 black==24.8.0

      - name: Ruff (lint)
        run: ruff check .

      - name: Black (format check)
        run: black --check --line-length 100 .

  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          # Pas de dépendances runtime pour l'instant,
          # mais gardons la commande pour évoluer facilement
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: python -m unittest discover -s tests -p "test_*.py" -v